// Resolve a job URL to its tailored resume PDF.
//
// Strategy:
//   1. Find the report row in data/applications.md whose Notes/Report column
//      references the URL (or whose company+role best matches).
//   2. Parse the report filename to get its slug: `{num}-{slug}-{date}.md`.
//      The slug after the leading number is exactly the slug used by the
//      tailored PDF: `cv-deepak-mallampati-{slug}-{date}.pdf`.
//   3. Search output/**/cv-deepak-mallampati-{slug}-*.pdf, prefer most recent.
//
// If the URL isn't tracked yet, fall back to slug derived from
// {company}-{role} arguments; finally, fall back to the canonical CV PDF
// generated by `npm run pdf`.
import { readFileSync, existsSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";

const PROJECT_ROOT = new URL("../../", import.meta.url).pathname;

export function findReportForUrl(url) {
  const reportsDir = join(PROJECT_ROOT, "reports");
  if (!existsSync(reportsDir)) return null;
  // Newest first (higher report number wins; ties broken by date in filename).
  const files = readdirSync(reportsDir)
    .filter((f) => f.endsWith(".md"))
    .sort((a, b) => {
      const na = parseInt(a.match(/^(\d+)/)?.[1] ?? "0", 10);
      const nb = parseInt(b.match(/^(\d+)/)?.[1] ?? "0", 10);
      return nb - na;
    });
  for (const f of files) {
    const text = readFileSync(join(reportsDir, f), "utf8");
    const m = text.match(/\*\*URL:\*\*\s*(\S+)/);
    if (m && m[1].trim() === url.trim()) {
      return { file: f, path: join(reportsDir, f) };
    }
  }
  return null;
}

export function reportSlug(filename) {
  // `{NNN}-{slug}-{YYYY-MM-DD}.md` → `{slug}`
  const m = filename.match(/^\d+-(.+)-\d{4}-\d{2}-\d{2}\.md$/);
  return m ? m[1] : null;
}

export function findPdfForSlug(slug) {
  if (!slug) return null;
  const outputDir = join(PROJECT_ROOT, "output");
  if (!existsSync(outputDir)) return null;
  // Walk dated subfolders newest-first.
  const days = readdirSync(outputDir)
    .filter((d) => /^\d{4}-\d{2}-\d{2}$/.test(d))
    .sort()
    .reverse();
  for (const day of days) {
    const dayDir = join(outputDir, day);
    if (!statSync(dayDir).isDirectory()) continue;
    const pdfs = readdirSync(dayDir).filter((f) => f.endsWith(".pdf"));
    const target = pdfs.find((f) =>
      f.startsWith(`cv-deepak-mallampati-${slug}-`)
    );
    if (target) return join(dayDir, target);
  }
  return null;
}

export function resolveResume(url, fallbackSlug = null) {
  const report = findReportForUrl(url);
  let slug = report ? reportSlug(report.file) : fallbackSlug;
  let pdf = slug ? findPdfForSlug(slug) : null;

  // Last-resort fallback: canonical CV in output/.
  if (!pdf) {
    const outputDir = join(PROJECT_ROOT, "output");
    const canonical = join(outputDir, "cv-deepak-mallampati.pdf");
    if (existsSync(canonical)) pdf = canonical;
  }

  return { url, report, slug, pdf };
}
